spring:
  liquibase:
    enabled: false
  mvc:
    static-path-pattern: '/resources/**'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: true
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5434/inventory
    password: password
    username: postgres
server:
  port: 8086
  servlet:
    session:
      timeout: 30m
logging:
  level:
    root: INFO