spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/inventory
    password: password
    username: postgres
server:
  port: 8086